#!/usr/bin/env zsh

export POWER_DEVICE_MACBOOK=24
export POWER_DEVICE_MACBOOK_NAME='macbook'

export POWER_DEVICE_MACBOOK_MONITOR=23
export POWER_DEVICE_MACBOOK_MONITOR_NAME='macbook_monitor'

export POWER_DEVICE_WORKSTATION_MONITOR_LEFT=22
export POWER_DEVICE_WORKSTATION_MONITOR_LEFT_NAME='workstation_monitor_left'

export POWER_DEVICE_CAMERA_ATIK_RED=21
export POWER_DEVICE_CAMERA_ATIK_RED_NAME='camera_atik_red'

export POWER_DEVICE_ICC1=20
export POWER_DEVICE_ICC1_NAME='icc1'

export POWER_DEVICE_CAMERA_SBIG_STX=19
export POWER_DEVICE_CAMERA_SBIG_STX_NAME='camera_sbig_stx'

export POWER_DEVICE_WORKSTATION_SPEAKERS=18
export POWER_DEVICE_WORKSTATION_SPEAKERS_NAME='workstation_speakers'

export POWER_DEVICE_WORKSTATION_MONITOR_RIGHT=17
export POWER_DEVICE_WORKSTATION_MONITOR_RIGHT_NAME='workstation_monitor_right'

export POWER_DEVICE_WORKSTATION=16
export POWER_DEVICE_WORKSTATION_NAME='workstation'

export POWER_DEVICE_FIBER=2
export POWER_DEVICE_FIBER_NAME='fiber'

export POWER_DEVICE_TEMP=1
export POWER_DEVICE_TEMP_NAME='temp'

typeset -A POWER_OUTLETS
POWER_OUTLETS=()
POWER_OUTLETS+=(${POWER_DEVICE_MACBOOK} ${POWER_DEVICE_MACBOOK_NAME})
POWER_OUTLETS+=(${POWER_DEVICE_MACBOOK_MONITOR} ${POWER_DEVICE_MACBOOK_MONITOR_NAME})
POWER_OUTLETS+=(${POWER_DEVICE_WORKSTATION_MONITOR_LEFT} ${POWER_DEVICE_WORKSTATION_MONITOR_LEFT_NAME})
POWER_OUTLETS+=(${POWER_DEVICE_CAMERA_ATIK_RED} ${POWER_DEVICE_CAMERA_ATIK_RED_NAME})
POWER_OUTLETS+=(${POWER_DEVICE_ICC1} ${POWER_DEVICE_ICC1_NAME})
POWER_OUTLETS+=(${POWER_DEVICE_CAMERA_SBIG_STX} ${POWER_DEVICE_CAMERA_SBIG_STX_NAME})
POWER_OUTLETS+=(${POWER_DEVICE_WORKSTATION_SPEAKERS} ${POWER_DEVICE_WORKSTATION_SPEAKERS_NAME})
POWER_OUTLETS+=(${POWER_DEVICE_WORKSTATION_MONITOR_RIGHT} ${POWER_DEVICE_WORKSTATION_MONITOR_RIGHT_NAME})
POWER_OUTLETS+=(${POWER_DEVICE_WORKSTATION} ${POWER_DEVICE_WORKSTATION_NAME})
POWER_OUTLETS+=(${POWER_DEVICE_FIBER} ${POWER_DEVICE_FIBER_NAME})
POWER_OUTLETS+=(${POWER_DEVICE_TEMP} ${POWER_DEVICE_TEMP_NAME})
export POWER_OUTLETS

typeset -A POWER_DEVICES
POWER_DEVICES=()
for outlet in ${(@k)POWER_OUTLETS}; do
    local device="${POWER_OUTLETS[${outlet}]}"
    POWER_DEVICES+=(${device} ${outlet})
done
export POWER_DEVICES
