#!/usr/bin/env zsh

export POWER_ADDRESS=power
export POWER_USER=panda

export POWER_DEVICE_MACBOOK=1
export POWER_DEVICE_MACBOOK_NAME='macbook'

export POWER_DEVICE_MACBOOK_MONITOR=2
export POWER_DEVICE_MACBOOK_MONITOR_NAME='macbook_monitor'

export POWER_DEVICE_CAMERA_ATIK_RED=15
export POWER_DEVICE_CAMERA_ATIK_RED_NAME='camera_atik_red'

export POWER_DEVICE_CAMERA_SBIG_STX=16
export POWER_DEVICE_CAMERA_SBIG_STX_NAME='camera_sbig_stx'

export POWER_DEVICE_ICC1=23
export POWER_DEVICE_ICC1_NAME='icc1'

export POWER_DEVICE_TEMP=24
export POWER_DEVICE_TEMP_NAME='temporary'

typeset -A POWER_OUTLETS
POWER_OUTLETS=()
POWER_OUTLETS+=(${POWER_DEVICE_TEMP} ${POWER_DEVICE_TEMP_NAME})
POWER_OUTLETS+=(${POWER_DEVICE_ICC1} ${POWER_DEVICE_ICC1_NAME})
POWER_OUTLETS+=(${POWER_DEVICE_CAMERA_ATIK_RED} ${POWER_DEVICE_CAMERA_ATIK_RED_NAME})
POWER_OUTLETS+=(${POWER_DEVICE_CAMERA_SBIG_STX} ${POWER_DEVICE_CAMERA_SBIG_STX_NAME})
POWER_OUTLETS+=(${POWER_DEVICE_MACBOOK_MONITOR} ${POWER_DEVICE_MACBOOK_MONITOR_NAME})
POWER_OUTLETS+=(${POWER_DEVICE_MACBOOK} ${POWER_DEVICE_MACBOOK_NAME})
export POWER_OUTLETS

typeset -A POWER_DEVICES
POWER_DEVICES=()
for outlet in ${(@k)POWER_OUTLETS}; do
    local device="${POWER_OUTLETS[${outlet}]}"
    POWER_DEVICES+=(${device} ${outlet})
done
export POWER_DEVICES
